config/routes.rb
NewAuthDemo::Application.routes.draw do
  resources :users, :only => [:create, :new, :show]
  resource :session, :only => [:create, :destroy, :new]

  get "/sovietunion" => 'static_pages#sovietunion'
  get "/help" => 'static_pages#help'
  get "/partners" => 'static_pages#partners'
  get "/shop" => 'static_pages#shop'
  get "/home" => 'static_pages#home'

  root :to => "users#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, :only => [:new, :create]
  before_action :require_signed_in!, :only => [:destroy]

  def new
  end

  def create
    @user = User.find_by_credentials(
      user_params[:username],
      user_params[:password]
    )

    if @user
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def sovietunion
  end

  def help
  end

  def partners
  end

  def shop
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewAuthDemo</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target=".sidebar">

  <nav >
    <div class="navbar-header">
      <button class="navbar-toggle collapsed"
      data-toggle="collapse"
      data-target="#nav-bar-links">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_url %>">Vodkafy Your Life!</a>
  </div>
  <div class="collapse navbar-collapse" id="nav-bar-links">
    <ul class="nav navbar-nav nav-pills">
      <li>
        <a href="<%= home_url %>">Home</a>
      </li>
      <li>
        <a href="<%= sovietunion_url %>">Soviet Union</a>
      </li>
      <li>
        <a href="<%= help_url %>">Getting Help</a>
      </li>
      <li>
        <a href="<%= partners_url %>">Partners</a>
      </li>
      <li>
        <a href="<%= shop_url %>">Shop Vodkafy</a>
      </li>
      <% if signed_in? %>
      <li>
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
            <%= current_user.username %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "My Page", user_url(current_user)%></li>
            <li><%= button_to "Sign Out", session_url, :method => :delete, :class => "btn btn-default" %></li>
          </ul>
        </div>
      </li>
      <% else %>
      <li>
        <button class="btn btn-primary" data-toggle="modal" data-target="#signInModal">
          Sign In
        </button>
        <div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <!-- <h4 class="modal-title">Sign In</h4> -->
              </div>
              <div class="modal-body">
                <%= render "sessions/form", user: current_user ? current_user : User.new() %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
      </li>

      <% end %>
    </ul>
  </div>
</nav>


<hr>

<% if flash[:errors] %>
<h3>Please fix the following errors:</h3>
<ul>
  <% flash[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

<div class="container"><%= yield %></div>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<div class="alert alert-danger no-email" role="alert">You must provide your email!</div>
<div class="alert alert-danger no-story" role="alert">You must provide your sob story</div>
<div class="row">
  <div class="col-xs-6">
    <form>
      <label class="col-xs-9">Tell Us About Your Struggles With Alcoholism</label>
      <div class="form-group ">
        <textarea id="help-problem" class="col-xs-9"></textarea>
      </div>
      <br>
      <br>
      <br>
      <br>
      <label class="col-xs-9">Your Email</label>
      <div class="form-group">
        <input id="help-email" type="text" class="col-xs-9">
      </div>
      <div class="form-group col-xs-12">
        <br>
        <input type="button" id="get-help" class="btn btn-primary" value="Get Help">
      </div>
    </form>
  </div>
  <div class="col-xs-6">

    <table class="table table-striped">
      <thead>
        <th>Facility Name</th>
        <th>Treatment Price</th>
      </thead>
      <tr>
        <td>Liquor Store</td>
        <td>12 per handle</td>
      </tr>
      <tr>
        <td>Death</td>
        <td>Free!!! :)</td>
      </tr>
      <tr>
        <td>The Continental</td>
        <td>$10 for 5 shots</td>
      </tr>
      <tr>
        <td>AppAcademy</td>
        <td>18%</td>
      </tr>
    </table>
    <br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

app/views/static_pages/home.html.erb
<h1>Home</h1>
<div class="row">
  <div class="col-xs-8">
    <div id="vodka-carousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#vodka-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#vodka-carousel" data-slide-to="1"></li>
        <li data-target="#vodka-carousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag("balance.jpg", alt: "balance") %>
        </div>

        <div class="item">
          <%= image_tag("party.jpg", alt: "party") %>
        </div>

        <div class="item">
          <%= image_tag("speakrussian.jpg", alt: "speakrussian") %>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#vodka-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#vodka-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-10 vodka-info">
    <h2 id="history-of-vodka">History Of Da Vodka</h2>
    <p>Scholars debate the beginnings of vodka. It is a contentious issue because very little historical material is available. Vodka originated in Eastern Europe. The first production was either in  <a href="#" data-toggle="tooltip" title="Read About Poland">Poland</a> in the 8th century or in the area of today's  <a href="#" data-toggle="tooltip" title="Motherland!">Russia</a> in the late 9th century according to different sources. According to the <a href="#" data-toggle="tooltip" title="GVA Site">Gin and Vodka Association (GVA)</a>, the first distillery was documented over three hundred years later at Khlynovsk as reported in the Vyatka Chronicle of 1174. For many centuries, beverages differed significantly compared to the vodka of today, as the spirit at that time had a different flavor, color and smell, and was originally used as  <a href="#" data-toggle="tooltip" title="You probably need this!">medicine</a>. It contained little alcohol, an estimated maximum of about 14%, as only this amount can be attained by natural fermentation. The <a href="#" data-toggle="tooltip" title="What is that?">still</a>, allowing for distillation ("burning of wine") and increased purity and alcohol content was invented in the 8th century </p><p>
      A type of distilled liquor designated by the Russian word vodka came to Russia in the late 14th century. In 1386, the Genoese ambassadors brought the first aqua vitae ("the water of life") to Moscow and presented it to Grand Duke Dmitry Donskoy. The liquid obtained by distillation of grape must was thought to be a concentrate and a "spirit" of wine (spiritus vini in Latin), from where came the name of this substance in many European languages (like English spirit, or Russian спирт, spirt).</p><p>

      According to a legend, around 1430, a monk named Isidore from Chudov Monastery inside the Moscow Kremlin made a recipe of the first Russian vodka.[23] Having a special knowledge and distillation devices, he became the creator of a new, higher quality type of alcoholic beverage. This "bread wine", as it was initially known, was for a long time produced exclusively in the Grand Duchy of Moscow and in no other principality of Rus' (this situation persisted until the era of industrial production). Thus, this beverage was closely associated with Moscow.</p><p>

      Until the mid-18th century, the drink remained relatively low in alcohol content, not exceeding 40% ABV. Multiple terms for the drink were recorded, sometimes reflecting different levels of quality, alcohol concentration, filtering, and the number of distillations; most commonly, it was referred to as "burning wine", "bread wine", or even in some locations simply "wine". In some locations, grape wine may have been so expensive that it was a drink only for aristocrats. Burning wine was usually diluted with water to 24% ABV or less before drinking. It was mostly sold in taverns and was quite expensive. At the same time, the word vodka was already in use, but it described herbal tinctures (similar to absinthe), containing up to 75% ABV, and made for medicinal purposes.</p><p>

      The first written usage of the word vodka in an official Russian document in its modern meaning is dated by the decree of Empress Elizabeth of June 8, 1751, which regulated the ownership of vodka distilleries. By the 1860s, due to the government policy of promoting consumption of state-manufactured vodka, it became the drink of choice for many Russians. In 1863, the government monopoly on vodka production was repealed, causing prices to plummet and making vodka available even to low-income citizens. The taxes on vodka became a key element of government finances in Tsarist Russia, providing at times up to 40% of state revenue.[24] By 1911, vodka comprised 89% of all alcohol consumed in Russia. This level has fluctuated somewhat during the 20th century, but remained quite high at all times. The most recent estimates put it at 70% (2001). Today, some popular Russian vodka producers or brands are (amongst others) Stolichnaya and Russian Standard.[25]</p>

      <h2 id="vodka-today">Vodka Today</h2>
      <p>Vodka is on the forefront of modern vodka technology!! We keep prices low by buying in bulk and enhancing our vodka with rubbing alcohol and stain removers. It keeps you healthy, and your inside clean! Get yours today!</p>
      <p>
        In some countries, black-market or "bathtub" vodka is widespread because it can be produced easily and avoid taxation. However, severe poisoning, blindness, or death can occur as a result of dangerous industrial ethanol substitutes being added by black-market producers.[40] In March 2007 in a documentary, BBC News UK sought to find the cause of severe jaundice among imbibers of a "bathtub" vodka in Russia.[41] The cause was suspected to be an industrial disinfectant (Extrasept) – 95% ethanol but also containing a highly toxic chemical – added to the vodka by the illegal traders because of its high alcohol content and low price. Death toll estimates list at least 120 dead and more than 1,000 poisoned. The death toll is expected to rise due to the chronic nature of the cirrhosis that is causing the jaundice. However, there are also much higher estimates of the annual death toll (dozens or even hundreds of thousand of lives) produced by the vodka consumption in Russia.[42]
      </p>

      <h2 id="vodka-poem"> Here's A Poem</h2>
      <div class="view-content">
        <div>

          <h4>In praise of vodka</h4>
          <div class="poem-body poem-body-processed" unselectable="on"><p>
            In praise of vodka
          </p>
          <p>
            The taste they say for they must<br>
            or they feel that they must so they say<br>
            so they say they say <i>it has none</i><br><i>there's no taste, just water.</i>
          </p>
          <p>
            Water: the glassy lake Christ trod,<br>
            a bowl Herod rinsed his fingers in,<br>
            the rain falling on Troy's ruins,<br>
            last word last balm of the living.
          </p>
          <p>
            The same water, over and over. They say<br>
            for they say for they must so they say<br>
            we're running out running dry but there's always<br>
            the same amount as there's always been.
          </p>
          <p>
            It's we who are more. As for myself<br>
            I've spent all my days working out<br>
            just what little Miss Peaches might like<br>
            and I'm due a day off for the rest of my life.
          </p>
          <p>
            So out of the freezer the bottle, the green<br>
            frosty bottle, its label iced in cyrillic,<br>
            the glass and the water beside the glass.<br>
            Russische. Moskovskaya. Stolichnaya.
          </p>
          <p>
            So this is the taste of nothing:<br>
            nothing then nothing again. Nothing at all.<br>
            The taste of the air, of wind on the fields,<br>
            the wind through the long wet forest.
          </p>
          <p>
            A stream and the rain. I lie in my yard<br>
            and open my mouth to the moon and the down falling rain<br>
            and the rods of its words speak over my tougue<br>
            to the back of my throat and they say
          </p>
          <p>
            <i>Voda</i><br><i>Water</i><br><i>Vodka</i>
          </p>
          <p>
            <i>Voda</i><br><i>Water</i><br><i>Vodka</i>
          </p>
          <p>
            <i>Voda</i><br><i>Water</i><br><i>Vodka</i>
          </p>
          <p>
            <i>Voda</i><br><i>Water</i><br><i>Vodka</i>
          </p>
          <p>
            Vodka of course being the diminutive of 'water', 'voda' - a little water.
          </p>
          <p>from Shed: Poems 1980-2001 (Bloodaxe, 2001), © Ken Smith 2001, by permission of Bloodaxe Books. Recordings by permission of Bloodaxe Books Ltd and the British Council. www.bloodaxebooks.com www.britishcouncil.org/arts-literature</p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-2 sidebar">
    <ul class="nav nav-tabs" role="tablist">
      <li><a href="#history-of-vodka">History</a></li>
      <li><a href="#vodka-today">Vodka Today</a></li>
      <li><a href="#vodka-poem">Poem</a></li>
    </ul>
  </div>
</div>

app/views/static_pages/partners.html.erb
<h1>Partners</h1>

app/views/static_pages/shop.html.erb
<h1>Shop</h1>

app/views/static_pages/sovietunion.html.erb
<div class="jumbotron">
  <h1>Soviet Union</h1>

  <div class="col-xs-6">
    <p>In Soviet Union, vodka drink you!!</p>
  </div>
  <div class="col-xs-6">
    <p>In Soviet Union, every bar is being AA meeting time.</p>
  </div>
</div>

<div class="row">
  <h1>Meet our comrades!</h1>
</div>

<div class="row text-center">
  <div class="col-xs-3">
     <%= image_tag("stalin.jpeg", :alt => "stalin", class: "img-circle")  %>
     <h2>Hot Stalin</h2>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="col-xs-3">
     <%= image_tag("lenin.jpg", :alt => "lenin", class: "img-circle")  %>
     <h2>Lenin "the cute one"</h2>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <div class="col-xs-3">
     <%= image_tag("trotsky.jpeg", :alt => "stalin", class: "img-circle")  %>
     <h2>Foxy Trotsky</h2>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>

  <div class="col-xs-3">
     <%= image_tag("putin.jpeg", :alt => "stalin", class: "img-circle")  %>
     <h2>Pulchritudinous Putin</h2>
     <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
</div>

app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" class="btn btn-primary" value="<%= message %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>

<%= render "form", :user => @user %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>